name: tellevo_arq_limpia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  build_runner: ^2.4.13
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  http: ^1.2.2
  riverpod_annotation: ^3.0.0-dev.3
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
